name: terera_starter
description: A new Flutter application.



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  floating_bottom_navigation_bar: ^1.5.1
  url_launcher: ^6.0.7
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  at_client_mobile: ^1.0.0+8
  at_server_status: ^0.1.0+1
  at_demo_data: ^0.0.3+1
  modal_progress_hud: any
  at_onboarding_flutter: ^1.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
    - images/


